// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace webapi_iot_growdata5.Models;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<iounit_data_chronology> iounit_data_chronology { get; set; }

    public virtual DbSet<iounit_data_currently> iounit_data_currently { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<iounit_data_chronology>(entity =>
        {
            entity.HasKey(e => e.id).HasName("sensor_data_chronology_pkey");

            entity.Property(e => e.id).HasDefaultValueSql("nextval('sensor_data_chronology_id_seq'::regclass)");
            entity.Property(e => e.datetime).HasColumnType("timestamp without time zone");
            entity.Property(e => e.value_alphanumeric).HasMaxLength(25);
        });

        modelBuilder.Entity<iounit_data_currently>(entity =>
        {
            entity.HasKey(e => e.id_sdm).HasName("iounit_data_currently_pkey");

            entity.Property(e => e.direction_stamp_a).HasColumnType("timestamp without time zone");
            entity.Property(e => e.direction_stamp_b).HasColumnType("timestamp without time zone");
            entity.Property(e => e.last_processing).HasColumnType("timestamp without time zone");
            entity.Property(e => e.value_alphanumerical).HasMaxLength(25);
        });
        modelBuilder.HasSequence("sensor_data_chronology_id_seq");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}