// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace webapi_iot_growdata5.Models;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<iounit_configuration> iounit_configuration { get; set; }

    public virtual DbSet<iounit_data_chronology> iounit_data_chronology { get; set; }

    public virtual DbSet<iounit_data_currently> iounit_data_currently { get; set; }

    public virtual DbSet<iounit_data_masterdata> iounit_data_masterdata { get; set; }

    public virtual DbSet<iounit_measuring_units> iounit_measuring_units { get; set; }

    public virtual DbSet<iounit_type> iounit_type { get; set; }

    public virtual DbSet<iounit_user_roles> iounit_user_roles { get; set; }

    public virtual DbSet<iounit_users> iounit_users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<iounit_configuration>(entity =>
        {
            entity.HasKey(e => e.id).HasName("iounit_configuration_pkey");

            entity.Property(e => e.long_name).HasMaxLength(40);
            entity.Property(e => e.short_name).HasMaxLength(25);
        });

        modelBuilder.Entity<iounit_data_chronology>(entity =>
        {
            entity.HasKey(e => e.id).HasName("iounit_data_chronology_pkey");

            entity.Property(e => e.datetime).HasColumnType("timestamp without time zone");
            entity.Property(e => e.value_alphanumerical).HasMaxLength(25);
        });

        modelBuilder.Entity<iounit_data_currently>(entity =>
        {
            entity.HasKey(e => e.id_sdm).HasName("iounit_data_currently_pkey");

            entity.Property(e => e.direction_stamp_a).HasColumnType("timestamp without time zone");
            entity.Property(e => e.direction_stamp_b).HasColumnType("timestamp without time zone");
            entity.Property(e => e.last_processing).HasColumnType("timestamp without time zone");
            entity.Property(e => e.value_alphanumerical).HasMaxLength(25);
        });

        modelBuilder.Entity<iounit_data_masterdata>(entity =>
        {
            entity.HasKey(e => e.id).HasName("iounit_data_masterdata_pkey");

            entity.Property(e => e.long_name).HasMaxLength(40);
            entity.Property(e => e.short_name).HasMaxLength(25);
        });

        modelBuilder.Entity<iounit_measuring_units>(entity =>
        {
            entity.HasKey(e => e.id).HasName("iounit_measuring_units_pkey");

            entity.Property(e => e.long_name).HasMaxLength(40);
            entity.Property(e => e.short_name).HasMaxLength(25);
        });

        modelBuilder.Entity<iounit_type>(entity =>
        {
            entity.HasKey(e => e.id).HasName("iounit_type_pkey");

            entity.Property(e => e.long_name).HasMaxLength(40);
            entity.Property(e => e.py_drv_path).HasMaxLength(100);
            entity.Property(e => e.short_name).HasMaxLength(25);
        });

        modelBuilder.Entity<iounit_user_roles>(entity =>
        {
            entity.HasKey(e => e.id).HasName("iounit_user_roles_pkey");

            entity.Property(e => e.rolename).HasMaxLength(25);
        });

        modelBuilder.Entity<iounit_users>(entity =>
        {
            entity.HasKey(e => e.id).HasName("iounit_users_pkey");

            entity.Property(e => e.last_modify).HasColumnType("timestamp without time zone");
            entity.Property(e => e.pw_hash)
                .HasMaxLength(80)
                .HasDefaultValueSql("NULL::character varying");
            entity.Property(e => e.username).HasMaxLength(25);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}