// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi_iot_growdata5.Models;

public partial class iounit_data_chronology
{
    public int id { get; set; }

    public DateTime datetime { get; set; }

    public decimal? value_numeric { get; set; }

    public string value_alphanumeric { get; set; }

    public short? id_mu { get; set; }

    public short? id_sc { get; set; }
}