// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi_iot_growdata5.Models;

public partial class iounit_data_currently
{
    public int id_sdm { get; set; }

    public decimal? value_numerical { get; set; }

    public string value_alphanumerical { get; set; }

    public bool? write_direction { get; set; }

    public DateTime? direction_stamp_a { get; set; }

    public DateTime? direction_stamp_b { get; set; }

    public DateTime? last_processing { get; set; }
}