// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi_iot_growdata5.Models;

public partial class iounit_configuration
{
    public int id { get; set; }

    public string long_name { get; set; }

    public string short_name { get; set; }

    public short? id_st { get; set; }

    public short? id_sdm { get; set; }

    public string d1 { get; set; }

    public string d2 { get; set; }

    public string d3 { get; set; }

    public string d4 { get; set; }

    public string d5 { get; set; }

    public string d6 { get; set; }

    public string d7 { get; set; }

    public string d8 { get; set; }
}