// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi_iot_growdata5.Models;

public partial class iounit_user_roles
{
    public int id { get; set; }

    public string rolename { get; set; }
}