// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi_iot_growdata5.Models;

public partial class iounit_data_masterdata
{
    public int id { get; set; }

    public string long_name { get; set; }

    public string short_name { get; set; }

    public short? id_sc { get; set; }

    public short? id_mu { get; set; }
}